use crate::cityjson::core::cityobject::{CityObjectCore, CityObjectsCore};
use crate::prelude::*;
use std::fmt::{Display, Formatter};

#[derive(Debug, Clone)]
pub struct CityObjects<SS: StringStorage, RR: ResourceRef> {
    inner: CityObjectsCore<SS, RR, CityObject<SS, RR>>,
}

crate::macros::impl_cityobjects_methods!();

/// A CityObjects container using owned strings.
pub type OwnedCityObjects<RR> = CityObjects<OwnedStringStorage, RR>;

/// A CityObjects container using borrowed strings.
pub type BorrowedCityObjects<'a, RR> = CityObjects<BorrowedStringStorage<'a>, RR>;

#[derive(Debug, Default, Clone)]
pub struct CityObject<SS: StringStorage, RR: ResourceRef> {
    inner: CityObjectCore<SS, RR, CityObjectType<SS>>,
}

crate::macros::impl_cityobject_methods!(CityObjectType<SS>);

impl<SS: StringStorage, RR: ResourceRef> Display for CityObject<SS, RR> {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:#?}", self)
    }
}

#[derive(Debug, Default, Clone, Hash, Ord, PartialOrd, Eq, PartialEq)]
pub enum CityObjectType<SS: StringStorage> {
    Bridge,
    BridgePart,
    BridgeInstallation,
    BridgeConstructionElement,

    Building,
    BuildingPart,
    BuildingInstallation,

    CityFurniture,
    CityObjectGroup,
    #[default]
    Default,
    GenericCityObject,
    LandUse,

    PlantCover,
    SolitaryVegetationObject,
    TINRelief,
    WaterBody,
    Road,
    Railway,

    TransportSquare,
    Tunnel,
    TunnelPart,
    TunnelInstallation,

    Extension(SS::String),
}

impl<SS: StringStorage> Display for CityObjectType<SS> {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        if let CityObjectType::Extension(ext) = self {
            write!(f, "{}", ext)
        } else {
            write!(f, "{:#?}", self)
        }
    }
}

// Note: Tests for CityObjects container (test_basic_operations, test_filtering,
// test_bulk_operations, and test_attribute_filtering) are now generated by the
// impl_cityobjects_methods! macro and are available in the cityobjects_macro_tests module
