#!/usr/bin/env just --justfile

set dotenv-load := true

# Show the available recipes.
_default:
    just --list

# Run cargo clean.
clean:
    cargo clean

# Run cargo check across the crate.
check:
    cargo check --all-targets --all-features

# Build the crate.
build *args:
    cargo build --all-targets --all-features {{args}}

# Run clippy across the crate.
lint:
    cargo clippy --all-targets --all-features -- -Dclippy::all -Dclippy::pedantic

# Format the crate.
fmt:
    cargo fmt --all

# Run the test suite.
test:
    cargo test --lib --tests --all-features

# Build the documentation.
doc:
    RUSTDOCFLAGS="--cfg docsrs -Dwarnings" cargo +nightly doc --all-features --no-deps

# Run fmt, check, lint, test, and doc.
ci: fmt check lint test doc
