#!/usr/bin/env just --justfile

_default:
    just --list

check:
    cargo check --all-targets --all-features

build *args:
    cargo build --all-targets --all-features {{args}}

lint:
    cargo clippy --all-targets --all-features -- -Dclippy::all -Dclippy::pedantic

fmt:
    cargo fmt --all

test:
    cargo test

doc:
    cargo doc --all-features --no-deps

