-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS cityjson.citymodel DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS cityjson.citymodel DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS cityjson.extensions DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS cityjson.extensions DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS cityjson.extra_citymodel DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS cityjson.extra_citymodel DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS cityjson.extra_metadata DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS cityjson.extra_metadata DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS cityjson.citymodel_vertices DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS cityjson.citymodel_vertices DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS cityjson.citymodel_semantics DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS cityjson.citymodel_semantics DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS cityjson.semantics_children DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS cityjson.semantics_children DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS cityjson.semantic_attributes DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS cityjson.semantic_attributes DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS cityjson.citymodel;

CREATE TABLE IF NOT EXISTS cityjson.citymodel
(
    id serial,
    type_citymodel text NOT NULL,
    version text,
    metadata_id integer,
    transform_id integer,
    PRIMARY KEY (id)
);

COMMENT ON TABLE cityjson.citymodel
    IS 'Represents a city model, which is conceptually equivalent to a CityJSON object.';

DROP TABLE IF EXISTS cityjson.extension;

CREATE TABLE IF NOT EXISTS cityjson.extension
(
    id serial,
    name text NOT NULL,
    url text NOT NULL,
    version text NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE cityjson.extension
    IS 'Represents an Extension object.';

DROP TABLE IF EXISTS cityjson.extensions;

CREATE TABLE IF NOT EXISTS cityjson.extensions
(
    citymodel_id integer NOT NULL,
    extension_id integer NOT NULL,
    UNIQUE (citymodel_id, extension_id)
);

COMMENT ON TABLE cityjson.extensions
    IS 'A set of Extension objects related to a CityModel.';

DROP TABLE IF EXISTS cityjson.metadata;

CREATE TABLE IF NOT EXISTS cityjson.metadata
(
    id serial,
    geographical_extent geometry,
    identifier text,
    point_of_contact jsonb,
    reference_date date,
    reference_system text,
    title text,
    PRIMARY KEY (id)
);

COMMENT ON TABLE cityjson.metadata
    IS 'Represents a Metadata object.';

DROP TABLE IF EXISTS cityjson.attributes;

CREATE TABLE IF NOT EXISTS cityjson.attributes
(
    id serial,
    key text,
    type text,
    bool_value boolean,
    int_value bigint,
    uint_value bigint,
    float_value double precision,
    string_value text,
    geometry_value integer,
    PRIMARY KEY (id)
);

COMMENT ON TABLE cityjson.attributes
    IS 'Attribute values.';

DROP TABLE IF EXISTS cityjson.extra_citymodel;

CREATE TABLE IF NOT EXISTS cityjson.extra_citymodel
(
    citymodel_id integer,
    attribute_id integer
);

COMMENT ON TABLE cityjson.extra_citymodel
    IS 'Extra root attributes of a CityModel.';

DROP TABLE IF EXISTS cityjson.extra_metadata;

CREATE TABLE IF NOT EXISTS cityjson.extra_metadata
(
    metadata_id integer,
    attribute_id integer
);

COMMENT ON TABLE cityjson.extra_metadata
    IS 'Extra root attributes of a Metadata.';

DROP TABLE IF EXISTS cityjson.transform;

CREATE TABLE IF NOT EXISTS cityjson.transform
(
    id serial,
    scale_x double precision NOT NULL,
    scale_y double precision NOT NULL,
    scale_z double precision NOT NULL,
    translate_x double precision NOT NULL,
    translate_y double precision NOT NULL,
    translate_z double precision NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE cityjson.transform
    IS 'Represents a Transform object.';

DROP TABLE IF EXISTS cityjson.vertices;

CREATE TABLE IF NOT EXISTS cityjson.vertices
(
    id serial,
    point geometry NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE cityjson.vertices
    IS 'Represents the vertices of a CityModel';

DROP TABLE IF EXISTS cityjson.citymodel_vertices;

CREATE TABLE IF NOT EXISTS cityjson.citymodel_vertices
(
    citymodel_id integer,
    vertex_id integer
);

COMMENT ON TABLE cityjson.citymodel_vertices
    IS 'Connects a CityModel to a set of vertices';

DROP TABLE IF EXISTS cityjson.semantics;

CREATE TABLE IF NOT EXISTS cityjson.semantics
(
    id serial,
    type_semantic text NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE cityjson.semantics
    IS 'Stores Semantic objects.';

DROP TABLE IF EXISTS cityjson.citymodel_semantics;

CREATE TABLE IF NOT EXISTS cityjson.citymodel_semantics
(
    citymodel_id integer NOT NULL,
    semantic_id integer NOT NULL
);

COMMENT ON TABLE cityjson.citymodel_semantics
    IS 'Connects a set of Semantics to a CityModel.';

DROP TABLE IF EXISTS cityjson.semantics_children;

CREATE TABLE IF NOT EXISTS cityjson.semantics_children
(
    parent_id integer NOT NULL,
    child_id integer NOT NULL
);

COMMENT ON TABLE cityjson.semantics_children
    IS 'Hierarchy of Semantic objects.';

DROP TABLE IF EXISTS cityjson.semantic_attributes;

CREATE TABLE IF NOT EXISTS cityjson.semantic_attributes
(
    semantic_id integer NOT NULL,
    attribute_id integer NOT NULL
);

COMMENT ON TABLE cityjson.semantic_attributes
    IS 'Relates attributes to semantic objects.';

ALTER TABLE IF EXISTS cityjson.citymodel
    ADD FOREIGN KEY (metadata_id)
        REFERENCES cityjson.metadata (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS cityjson.citymodel
    ADD FOREIGN KEY (transform_id)
        REFERENCES cityjson.transform (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS cityjson.extensions
    ADD FOREIGN KEY (citymodel_id)
        REFERENCES cityjson.citymodel (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS cityjson.extensions
    ADD FOREIGN KEY (extension_id)
        REFERENCES cityjson.extension (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS cityjson.extra_citymodel
    ADD FOREIGN KEY (citymodel_id)
        REFERENCES cityjson.citymodel (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS cityjson.extra_citymodel
    ADD FOREIGN KEY (attribute_id)
        REFERENCES cityjson.attributes (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS cityjson.extra_metadata
    ADD FOREIGN KEY (metadata_id)
        REFERENCES cityjson.metadata (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS cityjson.extra_metadata
    ADD FOREIGN KEY (attribute_id)
        REFERENCES cityjson.attributes (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS cityjson.citymodel_vertices
    ADD FOREIGN KEY (citymodel_id)
        REFERENCES cityjson.citymodel (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS cityjson.citymodel_vertices
    ADD FOREIGN KEY (vertex_id)
        REFERENCES cityjson.vertices (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS cityjson.citymodel_semantics
    ADD FOREIGN KEY (citymodel_id)
        REFERENCES cityjson.citymodel (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS cityjson.citymodel_semantics
    ADD FOREIGN KEY (semantic_id)
        REFERENCES cityjson.semantics (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS cityjson.semantics_children
    ADD FOREIGN KEY (parent_id)
        REFERENCES cityjson.semantics (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS cityjson.semantics_children
    ADD FOREIGN KEY (child_id)
        REFERENCES cityjson.semantics (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS cityjson.semantic_attributes
    ADD FOREIGN KEY (semantic_id)
        REFERENCES cityjson.semantics (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS cityjson.semantic_attributes
    ADD FOREIGN KEY (attribute_id)
        REFERENCES cityjson.attributes (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;

END;