site_name: cjlib
nav:
  - Home: index.md
  - Engineering choices: engineering.md
  - Guide: guide.md
  - Examples: examples.md
  - FAQ: faq.md
theme:
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  # admonitions
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  # content tabs
  - pymdownx.tabbed:
      alternate_style: true
  # tasklists
  - pymdownx.tasklist:
      custom_checkbox: true
  # emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # footnotes
  - footnotes
