//! # CityObject
//!
//! Represents a [CityObject object](https://www.cityjson.org/specs/1.1.3/#the-different-city-objects).
//!
//! Properties that are specific to certain type of CityObjects need to be set as `extra`
//! attributes. For example the `address` member of the `Bridge` and `Building` types,
//! or the `children_roles` member of the `CityObjectGroup`.

use crate::cityjson::core::cityobject::{CityObjectCore, CityObjectsCore};
use crate::prelude::*;
use std::fmt::{Display, Formatter};

/// A container for efficiently storing and accessing CityObject instances.
///
/// This container provides fast random access, iteration, and mutation capabilities,
/// suitable for managing thousands of CityObjects in a CityJSON model.
///
/// # Type Parameters
///
/// * `SS` - The string storage strategy to use (e.g., `OwnedStringStorage` or `BorrowedStringStorage`)
/// * `RR` - The resource reference type used for identifying objects (e.g., `ResourceId32`)
///
/// # Examples
///
/// ```
/// use cityjson::prelude::*;
/// use cityjson::v1_1::{CityObjects, CityObject, CityObjectType};
///
/// // Create a container for CityObjects
/// let mut objects = CityObjects::<OwnedStringStorage, ResourceId32>::new();
///
/// // Add a building
/// let building = CityObject::new("id-1".to_string(), CityObjectType::Building);
/// let building_id = objects.add(building);
///
/// // Retrieve a CityObject by its ID
/// let retrieved_building = objects.get(building_id).unwrap();
/// assert_eq!(retrieved_building.type_cityobject(), &CityObjectType::Building);
/// ```
#[derive(Debug, Clone)]
pub struct CityObjects<SS: StringStorage, RR: ResourceRef> {
    inner: CityObjectsCore<SS, RR, CityObject<SS, RR>>,
}

crate::macros::impl_cityobjects_methods!();

/// A CityObjects container using owned strings.
pub type OwnedCityObjects<RR> = CityObjects<OwnedStringStorage, RR>;

/// A CityObjects container using borrowed strings.
pub type BorrowedCityObjects<'a, RR> = CityObjects<BorrowedStringStorage<'a>, RR>;

#[derive(Debug, Default, Clone)]
pub struct CityObject<SS: StringStorage, RR: ResourceRef> {
    inner: CityObjectCore<SS, RR, CityObjectType<SS>>,
}

crate::macros::impl_cityobject_methods!(CityObjectType<SS>);

impl<SS: StringStorage, RR: ResourceRef> Display for CityObject<SS, RR> {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:#?}", self)
    }
}

#[derive(Debug, Default, Clone, Hash, Ord, PartialOrd, Eq, PartialEq)]
pub enum CityObjectType<SS: StringStorage> {
    Bridge,
    BridgePart,
    BridgeInstallation,
    BridgeConstructiveElement,
    BridgeRoom,
    BridgeFurniture,
    Building,
    BuildingPart,
    BuildingInstallation,
    BuildingConstructiveElement,
    BuildingFurniture,
    BuildingStorey,
    BuildingRoom,
    BuildingUnit,
    CityFurniture,
    CityObjectGroup,
    #[default]
    Default,
    LandUse,
    OtherConstruction,
    PlantCover,
    SolitaryVegetationObject,
    TINRelief,
    WaterBody,
    Road,
    Railway,
    Waterway,
    TransportSquare,
    Tunnel,
    TunnelPart,
    TunnelInstallation,
    TunnelConstructiveElement,
    TunnelHollowSpace,
    TunnelFurniture,
    Extension(SS::String),
}

impl<SS: StringStorage> Display for CityObjectType<SS> {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        if let CityObjectType::Extension(ext) = self {
            write!(f, "{}", ext)
        } else {
            write!(f, "{:#?}", self)
        }
    }
}

// Note: Tests for CityObjects container (test_basic_operations, test_filtering,
// test_bulk_operations, and test_attribute_filtering) are now generated by the
// impl_cityobjects_methods! macro and are available in the cityobjects_macro_tests module
