set dotenv-load := true
datadir := "tests" / "data" / "downloaded"

# Create dir for downloaded files
_prepare:
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d {{datadir}} ]; then
      mkdir -p {{datadir}}
    fi

# Download test data for the benchmarks from the 3DBAG
_download-3dbag: _prepare
    #!/usr/bin/env bash
    set -euxo pipefail
    version="v20231008"
    tiles=( "10-356-724" )
    download_url="https://data.3dbag.nl/"$version"/tiles"
    for tile_id in "${tiles[@]}" ;
    do
      tile_path=${tile_id//[-]//}
      tile_filename=$tile_id".city.json.gz"
      wget $download_url"/"$tile_path"/"$tile_filename -O {{datadir}}"/"$tile_filename
      gunzip {{datadir}}"/"$tile_filename
    done
    wget "https://data.3dbag.nl/"$version"/metadata.json" -O {{datadir}}"/metadata.json"

# Download test data for the benchmarks from the 3D Basivoorziening
_download-3dbasisvoorziening: _prepare
    #!/usr/bin/env bash
    set -euxo pipefail
    version="2020"
    tiles=( "30gz1" )
    download_url="https://download.pdok.nl/kadaster/basisvoorziening-3d/v1_0//"$version"/volledig"
    for tile_id in "${tiles[@]}" ;
    do
      tile_filename=$tile_id"_"$version"_volledig.zip"
      wget $download_url"/"$tile_filename -O {{datadir}}"/"$tile_filename
      unzip {{datadir}}"/"$tile_filename -d {{datadir}}
      rm {{datadir}}"/"$tile_filename
    done

# Download test data for the benchmarks
download: _download-3dbag _download-3dbasisvoorziening

# Delete all downloaded files
clean:
    rm -rf {{datadir}}

# Build and open the crate documentation
doc:
    RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features --no-deps --open

# Run all benchmarks and generate the comparison plots. Requires a python virtualenv in "resources/compare_benchmarks/.venv"
bench: bench-speed bench-size bench-plot

bench-speed:
    cargo bench --bench speed --

bench-size:
    cargo bench --features datasize --bench datasize --

bench-plot:
    resources/compare_benchmarks/.venv/bin/python resources/compare_benchmarks/compare_benchmarks.py