#ifndef CJLIB_FFI_CORE_H
#define CJLIB_FFI_CORE_H

#pragma once

/* This file is generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Stable status codes for the shared C ABI.
 */
typedef enum cj_status_t {
  CJ_STATUS_SUCCESS = 0,
  CJ_STATUS_INVALID_ARGUMENT = 1,
  CJ_STATUS_IO = 2,
  CJ_STATUS_SYNTAX = 3,
  CJ_STATUS_VERSION = 4,
  CJ_STATUS_SHAPE = 5,
  CJ_STATUS_UNSUPPORTED = 6,
  CJ_STATUS_MODEL = 7,
  CJ_STATUS_INTERNAL = 8,
} cj_status_t;

/**
 * Stable error categories for the shared C ABI.
 */
typedef enum cj_error_kind_t {
  CJ_ERROR_KIND_NONE = 0,
  CJ_ERROR_KIND_INVALID_ARGUMENT = 1,
  CJ_ERROR_KIND_IO = 2,
  CJ_ERROR_KIND_SYNTAX = 3,
  CJ_ERROR_KIND_VERSION = 4,
  CJ_ERROR_KIND_SHAPE = 5,
  CJ_ERROR_KIND_UNSUPPORTED = 6,
  CJ_ERROR_KIND_MODEL = 7,
  CJ_ERROR_KIND_INTERNAL = 8,
} cj_error_kind_t;

/**
 * Stable root type discriminant for probed inputs.
 */
typedef enum cj_root_kind_t {
  CJ_ROOT_KIND_CITY_JSON = 0,
  CJ_ROOT_KIND_CITY_JSON_FEATURE = 1,
} cj_root_kind_t;

/**
 * Stable version discriminant for probed inputs.
 */
typedef enum cj_version_t {
  CJ_VERSION_UNKNOWN = 0,
  CJ_VERSION_V1_0 = 1,
  CJ_VERSION_V1_1 = 2,
  CJ_VERSION_V2_0 = 3,
} cj_version_t;

/**
 * Opaque model handle type.
 *
 * The ABI only ever passes pointers to this marker type. The actual storage is
 * a boxed `cjlib::CityModel` allocated by the Rust side.
 */
typedef struct cj_model_t {
  uint8_t _private[0];
} cj_model_t;

/**
 * Owned byte buffer returned across the ABI.
 */
typedef struct cj_bytes_t {
  uint8_t *data;
  uintptr_t len;
} cj_bytes_t;

/**
 * Probe result returned by the low-level ABI.
 */
typedef struct cj_probe_t {
  enum cj_root_kind_t root_kind;
  enum cj_version_t version;
  bool has_version;
} cj_probe_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

enum cj_status_t cj_model_free(struct cj_model_t *handle);

enum cj_status_t cj_bytes_free(struct cj_bytes_t bytes);

enum cj_error_kind_t cj_last_error_kind(void);

uintptr_t cj_last_error_message_len(void);

enum cj_status_t cj_last_error_message_copy(uint8_t *buffer,
                                            uintptr_t capacity,
                                            uintptr_t *out_len);

enum cj_status_t cj_clear_error(void);

enum cj_status_t cj_probe_bytes(const uint8_t *data, uintptr_t len, struct cj_probe_t *out_probe);

enum cj_status_t cj_model_parse_document_bytes(const uint8_t *data,
                                               uintptr_t len,
                                               struct cj_model_t **out_model);

enum cj_status_t cj_model_parse_feature_bytes(const uint8_t *data,
                                              uintptr_t len,
                                              struct cj_model_t **out_model);

enum cj_status_t cj_model_parse_feature_with_base_bytes(const uint8_t *feature_data,
                                                        uintptr_t feature_len,
                                                        const uint8_t *base_data,
                                                        uintptr_t base_len,
                                                        struct cj_model_t **out_model);

enum cj_status_t cj_model_serialize_document(const struct cj_model_t *model,
                                             struct cj_bytes_t *out_bytes);

enum cj_status_t cj_model_serialize_feature(const struct cj_model_t *model,
                                            struct cj_bytes_t *out_bytes);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CJLIB_FFI_CORE_H */
