#ifndef CJLIB_FFI_CORE_H
#define CJLIB_FFI_CORE_H

#pragma once

/* This file is generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Stable status codes for the shared C ABI.
 */
typedef enum cj_status_t {
  CJ_STATUS_SUCCESS = 0,
  CJ_STATUS_INVALID_ARGUMENT = 1,
  CJ_STATUS_IO = 2,
  CJ_STATUS_SYNTAX = 3,
  CJ_STATUS_VERSION = 4,
  CJ_STATUS_SHAPE = 5,
  CJ_STATUS_UNSUPPORTED = 6,
  CJ_STATUS_MODEL = 7,
  CJ_STATUS_INTERNAL = 8,
} cj_status_t;

/**
 * Stable error categories for the shared C ABI.
 */
typedef enum cj_error_kind_t {
  CJ_ERROR_KIND_NONE = 0,
  CJ_ERROR_KIND_INVALID_ARGUMENT = 1,
  CJ_ERROR_KIND_IO = 2,
  CJ_ERROR_KIND_SYNTAX = 3,
  CJ_ERROR_KIND_VERSION = 4,
  CJ_ERROR_KIND_SHAPE = 5,
  CJ_ERROR_KIND_UNSUPPORTED = 6,
  CJ_ERROR_KIND_MODEL = 7,
  CJ_ERROR_KIND_INTERNAL = 8,
} cj_error_kind_t;

/**
 * Stable root type discriminant for probed inputs.
 */
typedef enum cj_root_kind_t {
  CJ_ROOT_KIND_CITY_JSON = 0,
  CJ_ROOT_KIND_CITY_JSON_FEATURE = 1,
} cj_root_kind_t;

/**
 * Stable version discriminant for probed inputs.
 */
typedef enum cj_version_t {
  CJ_VERSION_UNKNOWN = 0,
  CJ_VERSION_V1_0 = 1,
  CJ_VERSION_V1_1 = 2,
  CJ_VERSION_V2_0 = 3,
} cj_version_t;

/**
 * Stable model type discriminant for `CityJSON` documents and features.
 */
typedef enum cj_model_type_t {
  CJ_MODEL_TYPE_CITY_JSON = 0,
  CJ_MODEL_TYPE_CITY_JSON_FEATURE = 1,
} cj_model_type_t;

/**
 * Stable geometry type discriminant for stored `CityJSON` geometries.
 */
typedef enum cj_geometry_type_t {
  CJ_GEOMETRY_TYPE_MULTI_POINT = 0,
  CJ_GEOMETRY_TYPE_MULTI_LINE_STRING = 1,
  CJ_GEOMETRY_TYPE_MULTI_SURFACE = 2,
  CJ_GEOMETRY_TYPE_COMPOSITE_SURFACE = 3,
  CJ_GEOMETRY_TYPE_SOLID = 4,
  CJ_GEOMETRY_TYPE_MULTI_SOLID = 5,
  CJ_GEOMETRY_TYPE_COMPOSITE_SOLID = 6,
  CJ_GEOMETRY_TYPE_GEOMETRY_INSTANCE = 7,
} cj_geometry_type_t;

/**
 * Opaque model handle type.
 *
 * The ABI only ever passes pointers to this marker type. The actual storage is
 * a boxed `cjlib::CityModel` allocated by the Rust side.
 */
typedef struct cj_model_t {
  uint8_t _private[0];
} cj_model_t;

/**
 * Owned byte buffer returned across the ABI.
 */
typedef struct cj_bytes_t {
  uint8_t *data;
  uintptr_t len;
} cj_bytes_t;

/**
 * Packed 3D coordinate copied across the ABI.
 */
typedef struct cj_vertex_t {
  double x;
  double y;
  double z;
} cj_vertex_t;

/**
 * Owned vertex buffer returned across the ABI.
 */
typedef struct cj_vertices_t {
  struct cj_vertex_t *data;
  uintptr_t len;
} cj_vertices_t;

/**
 * Packed UV coordinate copied across the ABI.
 */
typedef struct cj_uv_t {
  float u;
  float v;
} cj_uv_t;

/**
 * Owned UV buffer returned across the ABI.
 */
typedef struct cj_uvs_t {
  struct cj_uv_t *data;
  uintptr_t len;
} cj_uvs_t;

/**
 * Probe result returned by the low-level ABI.
 */
typedef struct cj_probe_t {
  enum cj_root_kind_t root_kind;
  enum cj_version_t version;
  bool has_version;
} cj_probe_t;

/**
 * Aggregate model inspection summary returned across the ABI.
 */
typedef struct cj_model_summary_t {
  enum cj_model_type_t model_type;
  enum cj_version_t version;
  uintptr_t cityobject_count;
  uintptr_t geometry_count;
  uintptr_t geometry_template_count;
  uintptr_t vertex_count;
  uintptr_t template_vertex_count;
  uintptr_t uv_coordinate_count;
  uintptr_t semantic_count;
  uintptr_t material_count;
  uintptr_t texture_count;
  uintptr_t extension_count;
  bool has_metadata;
  bool has_transform;
  bool has_templates;
  bool has_appearance;
} cj_model_summary_t;

/**
 * Capacity hints for bulk import and model-building paths.
 */
typedef struct cj_model_capacities_t {
  uintptr_t cityobjects;
  uintptr_t vertices;
  uintptr_t semantics;
  uintptr_t materials;
  uintptr_t textures;
  uintptr_t geometries;
  uintptr_t template_vertices;
  uintptr_t template_geometries;
  uintptr_t uv_coordinates;
} cj_model_capacities_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

enum cj_status_t cj_model_free(struct cj_model_t *handle);

enum cj_status_t cj_bytes_free(struct cj_bytes_t bytes);

enum cj_status_t cj_vertices_free(struct cj_vertices_t vertices);

enum cj_status_t cj_uvs_free(struct cj_uvs_t uvs);

enum cj_error_kind_t cj_last_error_kind(void);

uintptr_t cj_last_error_message_len(void);

enum cj_status_t cj_last_error_message_copy(uint8_t *buffer,
                                            uintptr_t capacity,
                                            uintptr_t *out_len);

enum cj_status_t cj_clear_error(void);

enum cj_status_t cj_probe_bytes(const uint8_t *data, uintptr_t len, struct cj_probe_t *out_probe);

enum cj_status_t cj_model_parse_document_bytes(const uint8_t *data,
                                               uintptr_t len,
                                               struct cj_model_t **out_model);

enum cj_status_t cj_model_parse_feature_bytes(const uint8_t *data,
                                              uintptr_t len,
                                              struct cj_model_t **out_model);

enum cj_status_t cj_model_parse_feature_with_base_bytes(const uint8_t *feature_data,
                                                        uintptr_t feature_len,
                                                        const uint8_t *base_data,
                                                        uintptr_t base_len,
                                                        struct cj_model_t **out_model);

enum cj_status_t cj_model_serialize_document(const struct cj_model_t *model,
                                             struct cj_bytes_t *out_bytes);

enum cj_status_t cj_model_serialize_feature(const struct cj_model_t *model,
                                            struct cj_bytes_t *out_bytes);

enum cj_status_t cj_model_get_summary(const struct cj_model_t *model,
                                      struct cj_model_summary_t *out_summary);

enum cj_status_t cj_model_get_metadata_title(const struct cj_model_t *model,
                                             struct cj_bytes_t *out_bytes);

enum cj_status_t cj_model_get_metadata_identifier(const struct cj_model_t *model,
                                                  struct cj_bytes_t *out_bytes);

enum cj_status_t cj_model_get_cityobject_id(const struct cj_model_t *model,
                                            uintptr_t index,
                                            struct cj_bytes_t *out_bytes);

enum cj_status_t cj_model_get_geometry_type(const struct cj_model_t *model,
                                            uintptr_t index,
                                            enum cj_geometry_type_t *out_type);

enum cj_status_t cj_model_copy_vertices(const struct cj_model_t *model,
                                        struct cj_vertices_t *out_vertices);

enum cj_status_t cj_model_copy_template_vertices(const struct cj_model_t *model,
                                                 struct cj_vertices_t *out_vertices);

enum cj_status_t cj_model_copy_uv_coordinates(const struct cj_model_t *model,
                                              struct cj_uvs_t *out_uvs);

enum cj_status_t cj_model_create(enum cj_model_type_t model_type, struct cj_model_t **out_model);

enum cj_status_t cj_model_reserve_import(struct cj_model_t *model,
                                         struct cj_model_capacities_t capacities);

enum cj_status_t cj_model_add_vertex(struct cj_model_t *model,
                                     struct cj_vertex_t vertex,
                                     uintptr_t *out_index);

enum cj_status_t cj_model_add_template_vertex(struct cj_model_t *model,
                                              struct cj_vertex_t vertex,
                                              uintptr_t *out_index);

enum cj_status_t cj_model_add_uv_coordinate(struct cj_model_t *model,
                                            struct cj_uv_t uv,
                                            uintptr_t *out_index);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CJLIB_FFI_CORE_H */
